site_name: My Docs

nav:
    - Home: index.md
    - wiki_build: wiki_build.md
    - docker&k8s: dockerAndk8s/k8s_base_concept.md
    
theme:
  name: 'material'
  features:
    - search.suggest
    
plugins:
  - search:
      lang: en